---
title: "Graduate Application Essay"
author: "Claire To"
date: "2024-12-15"
categories: [reflections]
title-block-banner: true
---

Many graduate programs ask for two essays: a Personal History Statement and a Statement of Purpose, which is typically unique for each individual school. Here’s my Personal History Statement, where I share the story of my academic journey and everything that has shaped me along the way.

---

Standing on the edge of my first C++ course amidst the pandemic, I never imagined that I would one day strive to pursue a PhD in computer science. My journey through undergraduate education has been one of many twists and turns, filled with highs and lows, that have shaped who I am today. The experiences, relationships, and challenges have driven me in unanticipated ways, teaching me the importance of resilience, self-belief, and the powerful influence of those who believe in you.

At the start of my computer science courses, I was still in high school, dual-enrolled, navigating college-level coursework at a time when the world had moved online. While my introductory course was manageable, the transition to subsequent courses was challenging. Without a peer support system or opportunities for collaboration, I felt overwhelmed and was left to tackle my problems alone. These struggles destroyed my confidence, and for a long time, I convinced myself that this field was not for me. Although my parents were supportive of whichever path I pursued, their encouragement unintentionally reinforced my own belief that I was not capable of succeeding in computer science. 

The following year, I enrolled in community college full-time. I stepped away from computer science, exploring my other interests in business, economics, and language. In-person classes resumed, and during this time, I met friends majoring in computer science who inspired me to audit their classes, having already received credit. Revisiting the material gave me a stronger understanding and clarity that I hadn’t had before. I found myself capable of helping my friends with the coursework. By explaining concepts to others, I regained confidence in my own knowledge.

I came to appreciate the profound value of collaboration and discussion. When I found myself part of a more supportive and collaborative environment, I realized what I had initially missed out on by not having peers to work through difficult material with. Not only did learning become more manageable, but it taught me that working together can strengthen our understanding in ways that studying alone often cannot.

My foundation in programming strengthened unintentionally through this process, prompting me to push myself further in more advanced courses. A significant turning point came when I met Professor Gabriela Ernsberger. Her belief in me became a powerful motivator during my times of doubt. With her support, I excelled in my studies and performed exceptionally well.

Despite these accomplishments, I remained hesitant and felt un-belonging in computer science. When it was time to apply for university transfer, I felt uncertain whether I could handle upper-division courses and complete a degree in computer science. It wasn’t until my professors and peers urged me to apply, insisting that not doing so would be a missed opportunity, that I decided to take the risk. To my surprise, I received an offer of admission, and I committed to UCI’s Computer Science program along with some of the same friends who had helped influence my academic journey.

My transition to UCI was far from seamless. In my first quarter, I felt lost and overwhelmed by the large class sizes. The sheer number of students made it difficult to engage with professors and peers. Once again, I felt isolated and struggled to make lasting connections. The environment wasn’t conducive to my growth, and I began questioning whether I had made the right choice.

Everything changed when I enrolled in the Design and Analysis of Algorithms. I was excited about the class from the start; the topic sounded intriguing, and the energy in the room was unlike anything I had experienced. Despite the large class size, Professor Michael Shindler’s passion and enthusiasm created an engaging environment. He truly cares for all his students and wants the best for them. For the first time at UCI, I felt a sense of connection and community. His class reignited my passion, reminding me of the happiness I felt when I first began studying the subject. 

Nevertheless, my time in his class wasn’t without its struggles. Most of my classmates had taken the prerequisites at UCI, while I was one of the few relying on transfer credits. Consequently, I missed concepts unique to UCI’s version of the course, which were directly referenced with the expectation of prior study. As a result, I often felt behind and spent extra hours learning the concepts my classmates already knew, but I didn’t mind. My dedication kept me motivated, and I ultimately performed far better than I ever imagined. Rather than feeling exhausted by the end, I emerged more confident and with a new perspective on success: it’s not about being naturally gifted, but about persistence, resilience, and commitment. Surviving that experience gave me the courage to finish my degree and succeed in increasingly difficult courses. As I proceeded to subsequent classes, I found myself struggling less as my foundation grew stronger. The initial gaps I faced in understanding became stepping stones, and over time, I filled the gaps in my knowledge that I once lacked.

During these demanding times, I’ve grown not only as a student but also as a person. I’ve learned that failure and struggle aren’t setbacks; they’re growth opportunities. With each obstacle and mental barrier I overcome, I often look back and realize that the problems, that once felt insurmountable, now seem effortless, driving me to continue pushing the boundaries of my understanding. I’ve developed a profound appreciation for the power of belief in shaping success — both self-belief and the belief others have in us — understanding that the only limits to our abilities are those we set in our minds. Along the way, I’ve realized the true value of education. The further I go, the more my mind opens to new ways of thinking, with each discovery unlocking doors to even more questions and concepts to explore. This journey has deepened my understanding of the unique ways people think and the diverse perspectives that shape how we approach and interpret the world. 

These experiences have instilled in me a deep fulfillment for both learning and teaching, inspiring me to help others facing similar struggles. As the first in my family to pursue graduate education, I recognize the challenges of navigating unfamiliar paths. Throughout my journey, I discovered I am not only capable of adapting to new and unfamiliar environments but also thriving in them. I am confident that my adaptability and perseverance will allow me to navigate the PhD program and contribute to a community of growth and innovation. 

As I embark on this next chapter, I do so with gratitude for the people who have inspired and supported me, for the adversities that have made me stronger, and for the experiences that have brought me to this point. I look forward to continuing and embracing my journey in this academic environment that I’ve come to treasure, knowing that it will be filled with new challenges and opportunities for growth. And as I do so, I hope to be a source of guidance and encouragement for others who, like me, need someone to believe in them and to show them that anything is possible.
