---
title: "Nature, Nurture, and the Space Between"
author: "Claire To"
date: "2025-06-13"
categories: [reflections]
title-block-banner: true
---

I had a discussion with my family about nature vs. nurture — a deeply personal debate that reflects how we perceive our potential and how much we’re willing to endure to reach it.

My family believes that there is a personal limit to everything, and that no amount of training or effort can push you beyond a level you don’t innately possess. I agree with them to an extent when it comes to physical traits. Some physical attributes are essential for professional athletes, and many can’t attain them no matter how much they train. Even then, I’ve heard many stories where people have defied what should’ve been possible for them. On the other hand, when it comes to mental abilities, the situation feels more nuanced.

I believe in neuroplasticity — the ability of our brain to adapt and evolve. Skills such as public speaking, for example, seem to be one that can be learned and refined with enough training. I believe such skills don’t have a hard limit.

Maybe it’s overly optimistic, but when it comes to abilities such as intelligence, I think there’s more to it. I know that not everyone can be an Einstein, but I do think that most people never come close to reaching their true potential. Too often, people assume their limits are far lower than they actually are, and give up far too early when things begin to feel difficult. But it’s during these moments of struggle that we experience the most growth and emerge stronger on the other side.

From my experience in academia, it’s hard not to feel this way — especially when I’m surrounded by some of the most intelligent people. There are moments when I feel like I don’t belong, that I’m not cut out for this. As a result, I’ve nearly held myself back time and time again.

I was trapped my own self-doubt. I couldn’t escape the perspective I had built around something I hadn’t yet experienced and knew so little about from the outside. I simply believed that only those born with a certain level of intelligence could accomplish it and that I was nowhere near qualified.

It wasn’t until I met someone at the right moment who unknowingly changed my life that made me see everything in a different light. They once told me:

"I just wanted you to not worry too much about holding yourself back, because I don't think you should be the one holding yourself back. Let the world do that. Let the world tell you you're not good enough — and then ignore it."

Those words felt so empowering. It brought me a newfound feeling of hope and courage into my life. It made me realize how often I’d given up before the world ever had the chance to stop me.

In my moments of doubt, my parents were supportive of me stepping away. They didn’t see the value in pushing further when the challenges felt like too much of a struggle. They often praised how far I’d come, but at the same time, they would say they couldn’t have done it themselves.

I don’t think that’s true.

I never felt like I possessed innate talent in this field of study. Nothing has ever come easy to me; I had to work and struggle for every single piece of it. That’s exactly why I believe anyone can do it with enough stubbornness and perseverance.

In my times of uncertainty and doubt, it was those who had already been ahead of me and had gone through the same challenges that encouraged me to keep going. From community college to my bachelor’s degree and now pursuing a PhD, at each pivotal phase in my life, those who haven’t experienced the journey themselves feared it and questioned whether I could do it, while those who had walked the path believed it was possible.

If not for the people I met along the way, I may not be where I am today. Maybe I wouldn’t even believe in the possibility of reaching my limits.

I think it’s a tragedy that so many people give up the moment things get tough, and never discover how far they can really go. Like standing at the bottom of a mountain — you don’t know if you’ll make it over, but if you do, you might discover something you never imagined on the other side, and everything in between.

So why not try? Try until you fail, and only then will you discover your true limit.
