---
title: "Staying Long Enough to Belong"
author: "Claire To"
date: "2025-05-02"
categories: [reflections]
title-block-banner: true
---

I’ve come to realize that in every part of my life — dance, academics, and friendships — I’ve had to start from nothing. Yet, despite the challenges, I decided to try my best anyway.

## Dance

I often mention how I was forbidden to dance growing up. My parents discouraged it after my cousin majored in dance and struggled with her career. Still, I was always drawn to it through Just Dance, YouTube, and shows like Dance Moms. But I wasn’t allowed to try it myself until college. Maybe if I had gone to school in a more Asian-dominated area, it would’ve felt different, but in middle and high school, I never felt like I belonged there.

I started with nothing. I had no background in gymnastics or flexibility, and I could barely touch my toes. I didn’t even grow up listening to music. So when I started learning K-pop, I had no rhythm, no sense of sound. I danced by watching movements and matching them to lyrics, not by feeling the beat. But practicing through K-pop gave me enough confidence to step into real dance classes from hip-hop to modern. I especially loved modern dance because the movement felt freeing and expansive, even if I still lacked flexibility and couldn’t hear the music.

One style that always captivated me was contemporary. I would watch the dance department showcases and be in awe. It looked so fast, difficult, expressive, and deeply technical. I couldn’t imagine ever being good enough to take that class. For two years, I admired from afar.

But after graduating from community college, I felt this pull to try again. That summer, I trained to build the strength and flexibility I thought I’d need. I worked until I could achieve the splits and touch my toes with ease. When I finally enrolled in the contemporary class, I expected to struggle, but to my surprise, I kept up easily. In fact, I physically exceeded many of the dancers who had been dancing since they were kids.

That was a strange feeling. Everyone around me had ~20 years of dance under their belt. I had maybe two years. And yet, while my lack of technique showed, especially in musicality and turns, I could keep up. In some areas, I even excelled. My teacher often commented on the contrast: how I could be so flexible and controlled with so little background, and yet also so clearly new to dance in other ways. It’s like there are huge gaps in my ability, some natural strengths, and some deep holes.

I’m still improving. Month by month, I’m starting to hear the music more, and my turns are slowly getting better. The progress is slow, but I can feel it happening.

## Computer Science

With computer science, I’ve had more struggles than I can count. I didn’t understand pointers, and many concepts made me feel like I was drowning. At one point, I unofficially dropped out of the major, and it was the people around me who gave me the courage to try again. I made it through and transferred, but that wasn’t the end of the story. When I transferred, I realized I was severely behind, especially in algorithm design. I was missing prerequisite knowledge in data structures and algorithms, yet I was expected to keep up with students who had the proper background. That quarter nearly broke me. I was overwhelmed, stressed beyond belief, not just because the content was hard, but because I felt like I was letting down a professor who genuinely believed in me.

It didn’t end there either. The next quarter was somehow worse. The week we implemented Zip-Zip trees was the lowest point of my life. The structure was inspired by two data structures: Skip Lists, which I had never encountered, and balanced binary search trees, which I had never implemented. We were expected to code it in Python, a language I had never been properly taught. All of these were prerequisites UCI students had, but I was missing. It wasn’t the only struggle that quarter, but it was the one that hit me the hardest. I cried more during that quarter than in all my academic years combined.

Somehow, I’m still here. Still struggling, but learning to be proud because I made it through. I’m now pursuing a PhD in algorithms, the very subject I find the most difficult. I took introductory algorithms less than a year before applying. Some days I wonder how I got here, why I was accepted, whether I belong at all because when I say I’m under-qualified, I mean it. My lab-mates say it’s normal to feel that way, but they all had years of theory experience. I had none. Not only that, but I struggled in all my theory classes. They had a years of mathematical maturity, while I barely scraped by with limited math and dismissed classes like discrete math and statistics, thinking I’d never need them — only to now find that they’re the core language of my work.

I sit in theory talks and often don’t understand. Maybe I’ve trained myself to sit in confusion long enough to stay. Sometimes I tell people how lost I am, and some say it’s okay, while others look genuinely concerned. It feels conflicting. I’ve come to notice that those who have experienced more struggle and made it through tend to insist that I will be okay, while others are not so sure. I hope the handful of people who do believe in me are right, because I have placed my trust in them.

I’ve always looked up to the theory students. I can’t help but value intelligence and knowledge, and to me, they embodied both. I placed them on a pedestal: intimidating and inspiring. Sometimes I would peek into the lab through the window and see scribbles on the whiteboard. It felt like a different world, one I could never understand. It wasn’t imposter syndrome, at least not at first. Even before I ever considered pursuing theory, I was afraid of that lab. It carried a different air from the others. I never imagined I could be one of them. But somehow, that same lab has become my home, not because I suddenly understand everything, but because I stayed long enough to belong.

I’m not sure when that shift happened. Maybe it was the environments I was encouraged into, the people I met along the way, and my willingness to stay even when I felt like I didn’t belong. They say your environment shapes who you become, and maybe by putting myself in those rooms, I slowly and unintentionally rewrote my own path without realizing it. One moment later, I look around and realize I’m in the very room, among the very people, that once felt worlds away. And that makes me think maybe that’s what growth is. Not a dramatic transformation, but staying long enough in the discomfort until it starts to feel normal like home.

Starting theory research has made me cry. I felt so overwhelmed and terrified of disappointing my advisor and worried that he would give up on me. There were days I’d reread a single paragraph over and over, unable to make sense of it, but I still kept showing up and trying. Slowly, painfully but slowly, I’m staring to feel the slightest bit of progress. I can follow research meetings better. My lab-mate’s explanations are a bit clearer, when not too long ago, I couldn’t comprehend much of what he said. I can read and dissect a proof without immediately feeling overwhelmed. It’s still beyond difficult, but I’m starting to see small pieces click into place.

I don’t know how fast I’m supposed to be progressing. I don’t know what’s expected of me. But I hope that my effort will eventually be enough.

## Friendships

As for friends, I’ve had to rebuild my social circle from scratch. It forced me to take initiative and present myself as the person I wished I was. I was never that social girl, or the popular one, or the confident one, the one unafraid to speak up. I wanted to be her, but the gap between who I was and who I wanted to be felt so vast that it almost felt like acting. I was playing a role to be likable, someone accepted. 

Over time, I started to become that person. Not by pretending, but by slowly stepping into it until it felt natural. Now, I’m someone who can be warm and outgoing when needed, while still keeping my core beliefs and values unshakable and true to myself. Having had to start over before, I now trust that I’ll be okay wherever I go because I know how to rebuild from nothing.

Maybe all of these experiences are why I am who I am today. I don’t know what the future holds or if everything will crash and burn one day. But I want to believe that all this struggle wasn’t for nothing. That everything I’ve learned — the pain, the persistence, the growth — will lead to some kind of success, whatever that ends up meaning for me. I’ve rebuilt before. I’ve started from the beginning in so many areas of my life: physically, intellectually, socially. And I think, no matter what happens, I’ll be able to do it again if I need to.
