---
title: "The Hidden Value of Artistry"
author: "Claire To"
date: "2026-03-26"
categories: [reflections]
title-block-banner: true
---

I grew up in a world where artistic endeavors were dismissed, and pursuing them meant you were on the “wrong path” or wasting your time. It’s common for the STEM community to look down on the arts. To see them as useless, low-value, or an easy way out. While it’s true that STEM majors statistically land higher-paying jobs, I believe it’s ignorant to dismiss the arts entirely.

When I talk about artistic endeavors, I don’t mean mechanically playing an instrument, performing a dance move, or following instructions to create something—this is still closely related to STEM. I mean the *training of artistry*: opening your mind to different interpretations and creative expressions of yourself. Your artistry can’t be outsourced. It is what makes you, *you*. That’s why art has no single correct answer. No two people are the same or experience the world in the same way. Learning to convey your inner world to others is a difficult skill to obtain. It is what makes us human rather than robotic. Mechanics teach the language, but artistry is how you use it.

Many forms of art also train you to accept uncertainty, vulnerability, and the willingness to be seen. When there’s a right or wrong answer, it’s easy to hide behind an objective evaluation. But when you present a part of yourself for others to observe, the feeling is vastly different.

You might be thinking… what’s the point? I don’t need these skills to survive or make money. Yet these moments translate to people skills—how to be likable, hold attention, command a room, influence others, improvise, not shrink, and so on. It changes how you carry yourself in life, because you learn that your value isn’t how much you can memorize or score on an exam. It teaches you that who you are is enough.

After spending more time on art over the past few months, I see so much change now more than ever. My presence feels effortless. I can confidently walk to the front of a classroom without hesitation. Even when unexpected things happen during public speaking, I no longer crumble the way I might have a year or two ago when I would have wanted to die from fear and anxiety. I’ve learned to gesture, be a little silly, smile even when I make mistakes, and stand confidently. Well, maybe I still get a little nervous, but far less than ever before, and I believe it only gets easier.

I can’t guarantee that pursuing the arts will always lead to growth, because at the end of the day, every experience is what you make of it. Art requires an open mind, humility, vulnerability, and intentionality.
